stages:
- build
- deploy


variables:
  HOSTNAME: runbooks.alexos.dev


build:
  stage: build
  image: al3xos/ci-tools:latest
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
  - curl -sLo hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_0.83.1_Linux-64bit.tar.gz
  - tar -xzf hugo.tar.gz && mv hugo /usr/local/bin/ && rm -f LICENSE README.md hugo.tar.gz
  script:
  - ./build.sh
  artifacts:
    paths:
    - "app/www/**"

deploy:
  stage: deploy
  image: al3xos/ci-tools:latest
  dependencies:
  - build
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
  - echo "${RUN_CREDENTIALS}" | gcloud auth activate-service-account --key-file -
  script:
  - ./deploy.sh
